%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
#Camera.fx: 517.306408
#Camera.fy: 516.469215
#Camera.cx: 318.643040
#Camera.cy: 255.313989

#Camera.k1: 0.262383
#Camera.k2: -0.953104
#Camera.p1: -0.005358
#Camera.p2: 0.002628
#Camera.k3: 1.163314

#Camera.fx: 371.8473
#Camera.fy: 381.3091
#Camera.cx: 320.9910
#Camera.cy: 205.0340

#Camera.k1: -0.3170
#Camera.k2: 0.1323
#Camera.p1: -0.0071
#Camera.p2: -0.0032
#Camera.k3: -0.0286

#######con open cv camara USB
Camera.fx: 1325.97924
Camera.fy: 1330.81307
Camera.cx: 741.593031
Camera.cy: 390.353797

Camera.k1: -0.0498740237
Camera.k2: 2.37855374
Camera.p1: -0.00401647483
Camera.p2: -0.0130676265
Camera.k3: -0.0164104

#######con open cv camara del carrito 
#Camera.fx: 333.79544315
#Camera.fy: 305.15116515
#Camera.cx: 327.64126358
#Camera.cy: 184.33283913

#Camera.k1: -0.32926792
#Camera.k2: 0.10339377
#Camera.p1: 0.03420154
#Camera.p2: -0.00167815
#Camera.k3: -0.0164104


# Camera frames per second 
Camera.fps: 25

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

